### ISSUE TITLE
Inserting into my workflow

### ISSUE THREAD

**Issue by dgiovannelli** [SwiftDocOrg/github-wiki-publish-action#2]
Hi Mattt,
I'm new to GitHub and the community and I've been trying to make the publish action to work with no success.

Basically I have a repository where we are uploading a series of markdown documents (see [giovannellilab/protocols](https://github.com/giovannellilab/protocols)) and I would like the content of the wiki to be updated with pages coming from the repository. So far I have not found an easy to implement a solution. Your action seems exactly what I need, but being a novice I cannot get it to work.

I've already set up the access token as a secret and the first wiki page, but I'm failing to get the action to run.

Here is my current .yml file:

```
- name: Publish to GitHub Wiki
  uses: SwiftDocOrg/github-wiki-publish-action@1.0.0
  with:
    # A path to the directory of files to publish
    path: giovannellilab/protocols
````
Any suggestions on how to make it work or alternative solutions?
Thank you very much,
D
