### ISSUE TITLE
Sync a programmatically generated folder

### ISSUE THREAD

**Issue by hsnabszhdn** [SwiftDocOrg/github-wiki-publish-action#7]
Hey,

I have a dotnet core project committed to the repo. The wiki is setup on my project, but I don't have any folder committed to the source code for the wiki files.

What I do is run the dotnet core project in the Actions which generates the files in a folder in the bin directory. I want to push the content of this folder to the wiki. Is it possible?

Here is my pipeline:

```
name: .NET Core

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run
      run: dotnet "ConsoleApp1/bin/Release/netcoreapp3.1/ConsoleApp1.dll"
    - name: Publish
      uses: SwiftDocOrg/github-wiki-publish-action@1.0.0
      with:
        path: "ConsoleApp1/bin/Release/netcoreapp3.1/Files/Wiki/"
      env:
        GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
```

When I run this workflow, the Publish step shows this log:
```
Initialized empty Git repository in /tmp/ci-XXXXnJldLN/.git/
From https://github.com/itecompro/markdown-emoji-cheatsheet.wiki
 * branch            HEAD       -> FETCH_HEAD
On branch master
nothing to commit, working tree clean
Everything up-to-date
Branch 'master' set up to track remote branch 'master' from 'https://***@github.com/itecompro/markdown-emoji-cheatsheet.wiki.git'.
```
```
